version: '3.8'

services:
  db:
    image: postgres:15
    container_name: charme_next_db
    restart: always
    environment:
      POSTGRES_DB: charme
      POSTGRES_USER: charme_user
      POSTGRES_PASSWORD: charme_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
